### ISSUE TITLE
Планируется ли поддержка веба? 

### ISSUE THREAD

**Issue by VladislavYU** [shushper/cloudpayments#6]
Добрый день. Подскажите есть ли в планах сделать поддрежку для веба?

**Comment by shushper** [comment]
Здарвствуйте. Поддержка веба не планируется, потому что для этого не нужен какой-то sdk. Я так понию для веба лучше воспользоваться виджетом от cloudpayments. https://developers.cloudpayments.ru/#platezhnyy-vidzhet

**Comment by eldarkk** [comment]
интересно
